/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/components/**/*.{jsx,js}", "./src/app/**/*.{jsx,js}"],
  theme: {
    extend: {
      typography: ({ theme }) => ({
        theme: {
          css: {
            a: {
              textDecoration: "underline",
              textUnderlineOffset: "5px",
            },
            "--tw-prose-body": theme("colors.light[body]"),
            "--tw-prose-headings": theme("colors.light[heading]"),
            "--tw-prose-lead": theme("colors.pink[700]"),
            "--tw-prose-links": theme("colors.light[heading]"),
            "--tw-prose-bold": theme("colors.light[heading]"),
            "--tw-prose-counters": theme("colors.light[heading]"),
            "--tw-prose-bullets": theme("colors.pink[400]"),
            "--tw-prose-hr": theme("colors.light[border]"),
            "--tw-prose-quotes": theme("colors.light[heading]"),
            "--tw-prose-quote-borders": theme("colors.light[border]"),
            "--tw-prose-captions": theme("colors.pink[700]"),
            "--tw-prose-code": theme("colors.light[heading]"),
            "--tw-prose-pre-code": theme("colors.pink[100]"),
            "--tw-prose-pre-bg": theme("colors.pink[900]"),
            "--tw-prose-th-borders": theme("colors.pink[300]"),
            "--tw-prose-td-borders": theme("colors.pink[200]"),
            "--tw-prose-invert-body": theme("colors.dark[body]"),
            "--tw-prose-invert-headings": theme("colors.dark[heading]"),
            "--tw-prose-invert-lead": theme("colors.pink[300]"),
            "--tw-prose-invert-links": theme("colors.dark[heading]"),
            "--tw-prose-invert-bold": theme("colors.dark[heading]"),
            "--tw-prose-invert-counters": theme("colors.dark[heading]"),
            "--tw-prose-invert-bullets": theme("colors.pink[600]"),
            "--tw-prose-invert-hr": theme("colors.dark[border]"),
            "--tw-prose-invert-quotes": theme("colors.dark[heading]"),
            "--tw-prose-invert-quote-borders": theme("colors.dark[border]"),
            "--tw-prose-invert-captions": theme("colors.pink[400]"),
            "--tw-prose-invert-code": theme("colors.dark[heading]"),
            "--tw-prose-invert-pre-code": theme("colors.dark[heading]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.pink[600]"),
            "--tw-prose-invert-td-borders": theme("colors.pink[700]"),
          },
        },
      }),
      fontFamily: {
        sans: ["var(--font-space-grotesk)"],
        mono: ["var(--font-jetbrains-mono)"],
      },
      colors: {
        light: {
          body: "#615C6C",
          border: "#AFA8BA",
          heading: "#322E3D",
          "heading-variant": "#AFA8BA",
          icon: "#79747E",
          "icon-variant": "#7B7384",
          surface: "#FEF7FF",
          underline: "#AFA8BA",
        },
        dark: {
          body: "#A49EB0",
          border: "#4A435B",
          heading: "#E7DFF2",
          "heading-variant": "#645F6F",
          icon: "#645B76",
          "icon-variant": "#625D6D",
          surface: "#141218",
          underline: "#615C6C",
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
  darkMode: "class",
};
